replicaCount: 1

image:
  repository: 043210536673.dkr.ecr.us-east-1.amazonaws.com/comviva-argocd
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

# optional: override app name if you donâ€™t want to use Chart.yaml name
nameOverride: ""
fullnameOverride: ""

#configmaps
config:
  SPRING_PROFILES_ACTIVE: "dev"
  JAVA_OPTS: "-Xms512m -Xmx1024m"
